version: '3'
services:
  mongo:
    image: mongo
    ports:
      - 27017:27017
    volumes:
      - mongodb:/data/db
  pgAdmin:
    restart: always
    image: dpage/pgadmin4
    ports:
        - "8000:80"
    environment:
        PGADMIN_DEFAULT_EMAIL: admin@admin.com
        PGADMIN_DEFAULT_PASSWORD: admin
volumes:
 mongodb: